version: '3.7'
services:
  db:
    image: postgres:16-alpine
    ports:
      - "20530:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
volumes:
  db:

